version: "3.8"

#services/containers to run in application
services:
  app: #Main app #docker run -dp 3000:3000 -w /app -v "$(pwd):/app" --network stunning-tribble -e MYSQL_HOST=mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=secret -e MYSQL_DB=todos node:12-alpine sh -c "yarn install && yarn run dev"
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
       - 3000:3000
    working_dir: /app
    volumes:
       - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql: #mysql db, network alias will be made to match
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql #Use mysql-data volume
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  mysql-data:

    #equivalent to mysql launch:
    #docker run -d --network stunning-tribble --network-alias mysql -v mysql-data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=todos mysql:5.7
